<?php

/**
 * Drupal Module: Apsis One
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function apsisone_form_block_form_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['visibility']['apsisone_segments'])) {
    // Attach the library for the vertical tab.
    $form['visibility_tabs']['#attached']['library'][] = 'apsisone/block';
  }
}
